# fly.toml app configuration file generated for biocam-little-sun-6001 on 2024-11-17T19:52:01-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'biocam-little-sun-6001'
primary_region = 'gru'

[build]
  dockerfile = 'Dockerfile'

[env]
  FLASK_ENV = 'production'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
